reads_folder: "data/long-reads"
out_dir: "test_output"
genome_size: "2G"
min_len: "40"
min_q: "10"
medaka_model: "r104_e81_sup_g5015" 
asm_name: "test_proasellus_coiffaiti_G3_3X"
busco_db: "chlorophyta_obd10"
short_r1: "data/short-reads/r1.fastq.gz"
short_r2: "data/short-reads/r1.fastq.gz"
min_len_LR: "3000"
min_q_LR: "8"